### ISSUE TITLE
Ruby Example - Unable to find gem 'att-codekit'

### ISSUE THREAD

**Issue by jsgoecke** [attdevsupport/WebRTC-SampleApp#1]
Following the instructions here:

https://github.com/attdevsupport/WebRTC-SampleApp/tree/master/Ruby/app1

I am unable to find the 'att-codekit' gem in-spite of having added the recommended gem source:

```
gem sources
*** CURRENT SOURCES ***

https://rubygems.org/
http://lprod.code-api-att.com:8808
dactyl-7:app1 jsgoecke$ gem install att-codekit
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found  404 (http://lprod.code-api-att.com:8808/gems/att-codekit-4.3.2.gem)
```

**Comment by mattcobb** [comment]
Until that gem link gets sorted out, you mifht try to build the gem manualy from here. https://github.com/attdevsupport/codekit-ruby

**Comment by mattcobb** [comment]
The gem is there now, please retry it.

**Comment by jsgoecke** [comment]
Works a charm now, thanks!

bundle install
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Installing rake 10.4.2
Using immutable_struct 1.1.1
Installing json 1.8.2
Using mime-types 2.4.3
Installing netrc 0.10.2
Using rest-client 1.7.2
Using att-codekit 4.3.2 from source at .
Using bundler 1.7.11
Installing yard 0.8.7.6
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
